# Generated by Django 4.1.2 on 2022-10-23 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='photo',
        #     old_name='date_of_publications',
        #     new_name='date_of_publication',
        # ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
